geotab.addin.routingModule=function(api,state){"use strict";var devices=[],selectedDevice=null,routeStatus="none",deviationThreshold=100,mapAdapter=null,isInitialized=false;

function createMapAdapter(mapState){var polylines=[],markers=[];return{addPolyline:function(opts){var id="poly_"+Date.now()+"_"+Math.random();if(mapState&&mapState.addPolyline)mapState.addPolyline({id:id,coordinates:opts.coordinates,strokeColor:opts.color||"#3b82f6",strokeOpacity:opts.opacity||0.7,strokeWeight:opts.width||4});polylines.push(id);return id},removePolyline:function(id){if(mapState&&mapState.removePolyline)mapState.removePolyline(id);polylines=polylines.filter(function(p){return p!==id})},addMarker:function(opts){var id="marker_"+Date.now()+"_"+Math.random();if(mapState&&mapState.addMarker)mapState.addMarker({id:id,latitude:opts.lat,longitude:opts.lng,title:opts.label||"",color:opts.color||"#3b82f6"});markers.push(id);return id},removeMarker:function(id){if(mapState&&mapState.removeMarker)mapState.removeMarker(id);markers=markers.filter(function(m){return m!==id})},onMapClick:function(callback){if(state&&state.addEventListener)state.addEventListener("mapClick",function(evt){if(evt&&evt.detail)callback(evt.detail.latitude,evt.detail.longitude)})},clearAll:function(){polylines.forEach(function(id){if(mapState&&mapState.removePolyline)mapState.removePolyline(id)});markers.forEach(function(id){if(mapState&&mapState.removeMarker)mapState.removeMarker(id)});polylines=[];markers=[]}}}

function loadDevices(){api.call("Get",{typeName:"Device",resultsLimit:200},function(results){devices=results.map(function(d){return{id:d.id,name:d.name||"Dispositivo "+d.id,licensePlate:d.licensePlate||"",groups:d.groups||[]}});UIPanel.renderDevices(devices,null,handleDeviceSelect)},function(err){console.error("[RoutingAddin] Error cargando dispositivos:",err);devices=[];UIPanel.renderDevices([],null,null)})}

function saveRoute(routeData){api.call("Add",{typeName:"AddInData",entity:{addInId:"routingModule",data:JSON.stringify({route:routeData,deviceId:selectedDevice?selectedDevice.id:null,status:routeStatus,savedAt:new Date().toISOString()})}},function(){console.log("[RoutingAddin] Ruta guardada")},function(err){console.error("[RoutingAddin] Error guardando:",err)})}

function loadSavedRoute(){api.call("Get",{typeName:"AddInData",search:{addInId:"routingModule"}},function(results){if(results&&results.length>0){try{var saved=JSON.parse(results[0].data);if(saved.route){RouteBuilder.fromJSON(saved.route);routeStatus=saved.status||"none";UIPanel.updateStatusBadge(routeStatus)}}catch(e){console.warn("[RoutingAddin] Error parseando ruta:",e)}}},function(){})}

function handleMapClick(lat,lng){if(UIPanel.getActiveTab()!=="plan")return;RouteBuilder.addWaypoint(lat,lng)}
function handleRouteChanged(rs){UIPanel.renderWaypoints(rs.waypoints,{onRemove:function(i){RouteBuilder.removeWaypoint(i)},onReorder:function(f,t){RouteBuilder.moveWaypoint(f,t)}});UIPanel.updateRouteStats(rs.totalDistanceKm,rs.estimatedTimeMin);DeviationDetector.setPlannedRoute(rs.routeLinePoints)}
function handleDeviceSelect(deviceId){selectedDevice=devices.find(function(d){return d.id===deviceId})||null;UIPanel.renderDevices(devices,deviceId,handleDeviceSelect);UIPanel.setAssignEnabled(selectedDevice!==null&&RouteBuilder.getState().count>=2)}
function handleDeviceSearch(q){var filtered=devices.filter(function(d){var ql=q.toLowerCase();return d.name.toLowerCase().indexOf(ql)!==-1||(d.licensePlate&&d.licensePlate.toLowerCase().indexOf(ql)!==-1)});UIPanel.renderDevices(filtered,selectedDevice?selectedDevice.id:null,handleDeviceSelect)}
function handleAssign(){if(!selectedDevice||RouteBuilder.getState().count<2)return;routeStatus="pending";UIPanel.updateStatusBadge("pending");UIPanel.showAssignmentInfo(selectedDevice,RouteBuilder.getState(),"pending");UIPanel.showProgressContent(true);UIPanel.renderWaypointChecklist(RouteBuilder.getWaypoints(),[]);saveRoute(RouteBuilder.toJSON());UIPanel.switchTab("progress")}
function handleStartTracking(){if(!selectedDevice||routeStatus==="none")return;routeStatus="active";UIPanel.updateStatusBadge("active");UIPanel.showTrackingButtons(true);DeviationDetector.reset();TrackingEngine.start(selectedDevice.id,{intervalSec:15});ExceptionsHandler.start(selectedDevice.id,new Date().toISOString())}
function handleStopTracking(){TrackingEngine.stop();ExceptionsHandler.stop();UIPanel.showTrackingButtons(false)}

function handlePositionUpdate(data){if(data.error){console.warn("[RoutingAddin] Error GPS:",data.error);return}var result=DeviationDetector.evaluate(data.position,RouteBuilder.getWaypoints());var progress=DeviationDetector.calculateProgress(data.trail);if(result.isDeviated&&routeStatus!=="deviated"){routeStatus="deviated";UIPanel.updateStatusBadge("deviated")}else if(!result.isDeviated&&routeStatus==="deviated"){routeStatus="active";UIPanel.updateStatusBadge("active")}var rs=RouteBuilder.getState();var traveled=((rs.totalDistanceM*progress/100)/1000).toFixed(1)+" km";var startTime=TrackingEngine.getRouteStartTime();var diff=Math.floor((Date.now()-new Date(startTime).getTime())/1000);var elapsed=Math.floor(diff/60)+":"+(diff%60<10?"0":"")+(diff%60);UIPanel.updateProgress(progress,traveled,elapsed,result.isDeviated);UIPanel.renderWaypointChecklist(RouteBuilder.getWaypoints(),result.visitedWaypoints);if(progress>=98){routeStatus="completed";UIPanel.updateStatusBadge("completed");handleStopTracking();UIPanel.addAlert({type:"RUTA_COMPLETADA",time:new Date().toLocaleTimeString(),message:"Ruta completada exitosamente"})}}

function handleDeviationAlert(alert){UIPanel.addAlert(alert);if(alert.type==="DESVÍO_DETECTADO"&&selectedDevice){api.call("Add",{typeName:"TextMessage",entity:{device:{id:selectedDevice.id},messageContent:{message:"ALERTA: Desvío de ruta detectado ("+alert.distance+"m). Retorne a la ruta planificada.",contentType:"Normal"},isDirectionToVehicle:true}},function(){console.log("[RoutingAddin] Mensaje enviado al conductor")},function(err){console.warn("[RoutingAddin] Error enviando mensaje:",err)})}}

function handleNewException(ex){UIPanel.addException(ex)}
function handleThresholdChange(v){deviationThreshold=v;DeviationDetector.setThreshold(v)}
function handleClearRoute(){RouteBuilder.clearAll();routeStatus="none";selectedDevice=null;UIPanel.updateStatusBadge("none");UIPanel.showProgressContent(false);handleStopTracking();DeviationDetector.reset();ExceptionsHandler.reset()}

return{initialize:function(freshApi,st,callback){if(isInitialized){callback();return}mapAdapter=createMapAdapter(st);RouteBuilder.init(mapAdapter,handleRouteChanged);TrackingEngine.init(api,handlePositionUpdate);DeviationDetector.setThreshold(deviationThreshold);DeviationDetector.setAlertCallback(handleDeviationAlert);ExceptionsHandler.init(api,handleNewException);UIPanel.init({onTabChange:function(){},onThresholdChange:handleThresholdChange,onDeviceSearch:handleDeviceSearch,onExceptionFilter:function(type){UIPanel.filterExceptions(type)},onClearRoute:handleClearRoute,onOptimize:function(){},onAssign:handleAssign,onStartTracking:handleStartTracking,onStopTracking:handleStopTracking});mapAdapter.onMapClick(handleMapClick);loadDevices();loadSavedRoute();isInitialized=true;callback()},focus:function(freshApi,st){loadDevices();var rs=RouteBuilder.getState();if(rs.count>0)handleRouteChanged(rs)},blur:function(){if(RouteBuilder.getState().count>0)saveRoute(RouteBuilder.toJSON())}}};
